name: quickdrop_delivery
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  cloud_firestore: ^5.6.4
  intl: ^0.19.0
  google_sign_in: ^6.2.2
  rxdart: ^0.27.7
  flutter_svg: ^2.0.17
  cached_network_image: ^3.3.1
  extensions: 
    git: 
      url: https://github.com/4CROS2/string_extensions.git 
      ref: main
  apptoastification:
    git:
      url: https://github.com/4CROS2/apptoastification.git
      ref: main
  go_router: ^14.8.0
  shimmer: ^3.0.0
  permission_handler: ^11.4.0
  flutter_background_service: ^5.1.0
  location: ^8.0.0
  flutter_map: ^8.1.0
  flutter_compass: ^0.8.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null

flutter:
  generate: true
  uses-material-design: true
  assets: 
   - assets/images/svg/
   - assets/images/mark/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
    - family: Redhat
      fonts:
        - asset: assets/fonts/redhat_bold.ttf
          weight: 700
        - asset: assets/fonts/redhat_semi.ttf
          weight: 500
        - asset: assets/fonts/redhat_regular.ttf