name: quickdrop_delivery
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.3.2
  firebase_core: ^3.6.0
  equatable: ^2.0.5
  get_it: ^8.0.2
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  rxdart: ^0.28.0
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null

flutter:
  generate: true
  uses-material-design: true
  assets: 
   - assets/images/svg/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
    - family: Redhat
      fonts:
        - asset: assets/fonts/redhat_bold.ttf
          weight: 700
        - asset: assets/fonts/redhat_semi.ttf
          weight: 500
        - asset: assets/fonts/redhat_regular.ttf